### ISSUE TITLE
Cuando agrego una parada como favorita el corazón se vacía y cuando no la tengo agregada se encuentra lleno

### ISSUE THREAD

**Issue by ICT-Ronco** [xBaank/MadridTransporte#3]
**Descripción del error**
Una descripción clara y concisa de cuál es el error.

**Para Reproducir**
Pasos para reproducir el comportamiento:
1. Ir a '...'
2. Hacer clic en '....'
3. Desplazarse hacia abajo hasta '....'
4. Ver el error

**Comportamiento esperado**
Una descripción clara y concisa de lo que esperabas que sucediera.

**Capturas de pantalla**
Si es aplicable, añade capturas de pantalla para ayudar a explicar tu problema.

**Escritorio (por favor completa la siguiente información):**
 - SO: [por ejemplo, iOS]
 - Navegador [por ejemplo, chrome, safari]
 - Versión [por ejemplo, 22]

**Teléfono inteligente (por favor completa la siguiente información):**
 - Dispositivo: [por ejemplo, iPhone6]
 - SO: [por ejemplo, iOS8.1]
 - Navegador [por ejemplo, navegador por defecto, safari]
 - Versión [por ejemplo, 22]

**Contexto adicional**
Agrega cualquier otro contexto sobre el problema aquí.

**Comment by xBaank** [comment]
Duplicado de #4
