### ISSUE TITLE
Corazón vacío en paradas favoritas

### ISSUE THREAD

**Issue by ICT-Ronco** [xBaank/MadridTransporte#4]
**Descripción del error**
El corazón que se utiliza para distinguir las paradas marcadas como favoritas aparece relleno por defecto y se vacía al agregarlas

**Para Reproducir**
Pasos para reproducir el comportamiento:
1.buscar una parada
2.Guardar la parada como favorita

**Comportamiento esperado**
El corazón se rellena de un color 

**Capturas de pantalla**

**Teléfono inteligente (por favor completa la siguiente información):**
 - Dispositivo: iPhone 14 (pro)
 - SO: iOS 17.1.1
 - Navegador Safari
 - Versión 22

**Contexto adicional**
Agrega cualquier otro contexto sobre el problema aquí.

**Comment by xBaank** [comment]
Arreglado en https://github.com/xBaank/bus-tracker-front/commit/20a4e07c627b8ccea235c1c70cb5db6b31d92160
